name: CI Tests

on:
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'demo/**'
      - 'src/**'
      - 'vite.config.ts'
      - 'test/**'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linter
        run: pnpm run lint

      - name: Run Unit Tests with Coverage
        run: pnpm run test:coverage